url_categories:
  ctdt:
    - ctdt.ntu.edu.vn

  graduate:
    - pdtsaudaihoc.ntu.edu.vn

  finance:
    - phongkhtc.ntu.edu.vn

  student_procedure:
    - phongctsv.ntu.edu.vn
    - pdtdaihoc.ntu.edu.vn

  services:
    - thuvien.ntu.edu.vn
    - htdnhtsv.ntu.edu.vn

  admission:
    - tuyensinh.ntu.edu.vn
    - xettuyen.ntu.edu.vn
    - trungtamdtbd.ntu.edu.vn
